// <auto-generated />
using ApiExampleApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiExampleApi.Migrations
{
    [DbContext(typeof(EmployeeDataContext))]
    [Migration("20250311173226_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ApiExampleShared.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Research and Development",
                            Email = "nnorgue0@disqus.com",
                            FirstName = "Nonie",
                            LastName = "Norgue"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Research and Development",
                            Email = "bborgue0@disqus.com",
                            FirstName = "Bonie",
                            LastName = "Borgue"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Research and Development",
                            Email = "wworgue0@disqus.com",
                            FirstName = "Wonie",
                            LastName = "Worgue"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Research and Development",
                            Email = "ggorgue0@disqus.com",
                            FirstName = "Gonie",
                            LastName = "Gorgue"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Research and Development",
                            Email = "mmorgue0@disqus.com",
                            FirstName = "Monie",
                            LastName = "Morgue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
